build:
    image: mnbbrown/ci:latest
    commands:
        - make deps
        - make build-linux

publish:
    docker:
        registry: registry.matthewbrown.io
        repo: mnbbrown/hello
        tag: $$COMMIT
        storage_driver: overlay

notify:
    slack:
        webhook_url: https://hooks.slack.com/services/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
        channel: devops
        username: drone
