build:
    image: mnbbrown/ci:latest
    privileged: true
    commands:
        - make deps
        - make build-linux
        - scripts/docker.sh

notify:
    slack:
        webhook_url: https://hooks.slack.com/services/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
        channel: devops
        username: drone
